### ISSUE TITLE
Test Beta 3

### ISSUE THREAD

**Issue by DocCyblade** [DocCyblade/tkl-odoo#4]
Testing Beta 3
Keep this post check boxes only. If you find any errors don't post them here add a new issue and prefix it with `[v0.3] -` 
- [x] Install 
  - got internal server error at first attempt
    - had about 30 second delay after reboot to show up
- [x] See that Odoo is running (should land on the Database manager page
  - installed Database with entered password.
- [x] Change Admin Password in Odoo Database Manager (testing control)
- [x] install new database with new password
  worth check that openerp-server.con admin-db variable also changes  -- sometimes Odoo can "cache" this but not change it if not writing to openerp-server.conf properly
- [x] Install CRM Module
- [x] Install Online Billing
- [x] Install Sales Management
- [x]  Create a Customer
- [x]  Create a Quotation for the Customer
- [ ]  When quotation is saved, Choose Print  (or Email)

THIS DID NOT WORK.  I don't believe wkhtmltox (and other aspects) are installed.  (posting error code below)
- [ ]  See that a Formatted Doc Shows up
- [ ]  Ideally see that an Email goes out (should default to Localhost and might work)
- [ ]  Check that Git is applying to opt/openerp/odoo files

**Comment by l-arnold** [comment]
Installing now.

**Comment by l-arnold** [comment]
Installed Demo Data:
Chose "email"  got the following error code:  -> Focuses on wkhtmltopdf, but I believe (having tried 3 times) that we must use wkhtmltox with its dependencies.

ng
Reporting
Settings
 Administrator 

Sales
Customers
Leads 4
Opportunities 7
Quotations 2
Sales Orders 2
Phone Calls
Logged Calls
Products
Products
Product Variants
Products by Category
Tools
Deduplicate Contacts
Configuration
Contacts Segmentation
Unit of Measure Categories
 Address Book
 Phone Calls
 Product Categories & Attributes
 Leads & Opportunities
Powered by Odoo 
Quotations / SO006  
 Edit   Create
Print   More 
1 / 3 ( )
Send by Email Print Confirm Sale Cancel Quotation Draft Quotation  Quotation Sent  Sales Order  Done
Quotation SO006
Customer
Think Big Systems
One Lincoln Street
Boston 02203
United States
Date
09/28/2015 23:23:31
Reference/Description
Order Lines Other Information
Sequence 
Product 
Description 
Quantity
Unit Price 
Taxes 
Subtotal
[A2323] iPad Retina Display (16 GB, White, 2.4 GHz) PC Assamble + 2GB RAM   1.000   750.00      750.00

Untaxed Amount 
750.00 €
Taxes 
0.00 €
Total   750.00 €
 Following 
One follower Add others
 Administrator X
Send a message or Log an internal note

v7
Quotation created
Administrator updated document • 38 minutes ago • like

v7
    • Customer: Think Big Systems
    • Untaxed Amount:
    • Salesperson: Administrator
Administrator updated document • 38 minutes ago • like
ô
Search users...
  Odoo Support 
×
All records matching your current search filter will be mailed, not only the ids selected in the list view.
If you want to work only with selected ids, please uncheck the list header checkbox.
From
Subject
Recipients
Email mass mailing on the selected recordsthe current search filter. Followers of the document and
Notify followers
No threading for answers
Reply-To
 or  
Use template

×
Odoo
Odoo Server Error
Traceback (most recent call last):
  File "/opt/openerp/odoo/openerp/http.py", line 537, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/opt/openerp/odoo/openerp/http.py", line 574, in dispatch
    result = self._call_function(*_self.params)
  File "/opt/openerp/odoo/openerp/http.py", line 310, in _call_function
    return checked_call(self.db, *args, *_kwargs)
  File "/opt/openerp/odoo/openerp/service/model.py", line 113, in wrapper
    return f(dbname, _args, *_kwargs)
  File "/opt/openerp/odoo/openerp/http.py", line 307, in checked_call
    return self.endpoint(_a, *_kw)
  File "/opt/openerp/odoo/openerp/http.py", line 803, in __call__
    return self.method(_args, *_kw)
  File "/opt/openerp/odoo/openerp/http.py", line 403, in response_wrap
    response = f(_args, *_kw)
  File "/opt/openerp/odoo/addons/web/controllers/main.py", line 948, in call_kw
    return self._call_kw(model, method, args, kwargs)
  File "/opt/openerp/odoo/addons/web/controllers/main.py", line 940, in _call_kw
    return checked_call(request.db, _args, *_kwargs)
  File "/opt/openerp/odoo/openerp/service/model.py", line 113, in wrapper
    return f(dbname, _args, *_kwargs)
  File "/opt/openerp/odoo/addons/web/controllers/main.py", line 939, in checked_call
    return getattr(request.registry.get(model), method)(request.cr, request.uid, _args, *_kwargs)
  File "/opt/openerp/odoo/openerp/api.py", line 241, in wrapper
    return old_api(self, _args, *_kwargs)
  File "/opt/openerp/odoo/addons/email_template/wizard/mail_compose_message.py", line 54, in default_get
    res.get('model'), res.get('res_id'), context=context
  File "/opt/openerp/odoo/openerp/api.py", line 241, in wrapper
    return old_api(self, _args, *_kwargs)
  File "/opt/openerp/odoo/addons/email_template/wizard/mail_compose_message.py", line 104, in onchange_template_id
    values = self.generate_email_for_composer_batch(cr, uid, template_id, [res_id], context=context)[res_id]
  File "/opt/openerp/odoo/openerp/api.py", line 241, in wrapper
    return old_api(self, _args, *_kwargs)
  File "/opt/openerp/odoo/addons/email_template/wizard/mail_compose_message.py", line 168, in generate_email_for_composer_batch
    template_values = self.pool.get('email.template').generate_email_batch(cr, uid, template_id, res_ids, fields=fields, context=ctx)
  File "/opt/openerp/odoo/openerp/api.py", line 241, in wrapper
    return old_api(self, _args, *_kwargs)
  File "/opt/openerp/odoo/addons/email_template/email_template.py", line 514, in generate_email_batch
    result, format = self.pool['report'].get_pdf(cr, uid, [res_id], report_service, context=ctx), 'pdf'
  File "/opt/openerp/odoo/openerp/api.py", line 241, in wrapper
    return old_api(self, _args, *_kwargs)
  File "/opt/openerp/odoo/addons/report/models/report.py", line 274, in get_pdf
    paperformat, specific_paperformat_args, save_in_attachment
  File "/opt/openerp/odoo/openerp/api.py", line 241, in wrapper
    return old_api(self, _args, *_kwargs)
  File "/opt/openerp/odoo/addons/report/models/report.py", line 447, in _run_wkhtmltopdf
    wkhtmltopdf = [_get_wkhtmltopdf_bin()] + command_args + local_command_args
  File "/opt/openerp/odoo/addons/report/models/report.py", line 54, in _get_wkhtmltopdf_bin
    raise IOError
IOError

**Comment by l-arnold** [comment]
Will need to move to 4.0 .  General functions there but no email out rendering..
