### ISSUE TITLE
Landis Shakedown test part 1

### ISSUE THREAD

**Issue by DocCyblade** [DocCyblade/tkl-odoo#53]
Test will be done with VMWare Esx with
1 X CPU
1GB RAM
20GB HDD

Test one will install all modules available and test each one using CRUD and every option at least 3 times. 

Goal is to test all modules and options with limited resources. Will note any issues here. If issue is with resources will note that and retest in part 2

Keep list of things tested here only. Add comments if any issues only.
- List Checked off in separate comment below

Test List:
- [ ] ISO Live Preview (Basic new database and module) **Fails** with 512MB RAM would need 1GB
- [ ] ISO Install Guided Setup all
- [ ] ISO Install Guided Setup LVM (Defaults)
- [ ] First Boot: Signup for email alerts
- [ ] First Boot: Updates
- [ ] Create new database
- [ ] Update Company Info
- [ ] Add two users
- [ ] Delete user
- [ ] Install and configure all local modules
- [ ] Test Modules (Basic function of each)
- [ ] CRM
- [ ] Social Network
- [ ] Online Billing
- [ ] Point of Sale
- [ ] Project Management
- [ ] Notes
- [ ] Issue Tracking
- [ ] Accounting and Finance
- [ ] Survey
- [ ] Sales Management
- [ ] Warehouse Management
- [ ] Instant Messaging
- [ ] MRP
- [ ] Purchase Management
- [ ] Employee Directory
- [ ] Timesheets
- [ ] Recruitment Process
- [ ] Leave Management
- [ ] Expense Tracker
- [ ] Employee Appraisals
- [ ] Calendar
- [ ] Address Book
- [ ] Gamification
- [ ] Live Chat
- [ ] Odoo Live Support
- [ ] Lunch Orders
- [ ] Website Builder
- [ ] Blogs
- [ ] Online Events
- [ ] Forum
- [ ] eCommerce
- [ ] Fleet Management

**Comment by DocCyblade** [comment]
Keep list of things tested here only. Add comments if any issues only.

Test List:

   - [ ] Module Tested

**Comment by DocCyblade** [comment]
@l-arnold - Just beat the thing up as mush as you can. I don't want to add to it, just use whats installed. If there is a button, push it. If there is a knob turn it. Want to make sure our base appliance is very good base to build on.

**Comment by DocCyblade** [comment]
@l-arnold - This is the home stretch :-) We may even find bugs with Odoo, my focus is to make sure our install is as good as it can be and to knock out or find any thing we need to just document. We will find little things for sure, but I want to find show stopper bugs. Worst thing to do is have a new app in TKL that there was a hidden bug and some one gets turned off of TKL and/or Odoo. 

This is also an excuse for me to get to really know the product (as I will be using it for my self at some point)

**Comment by l-arnold** [comment]
Ok @DocCyblade   Will Do for sure.  I actually took Last Nights RC 1 and Put 700 names in it.  Definitely running better than the v 5 Beta I had it running on earlier.  

Important to watch what happens a few days later once and a while.

**Comment by DocCyblade** [comment]
@l-arnold - Sorry was updating the wrong issue! I am back to my own!

**Comment by l-arnold** [comment]
I need to update the "hard and soft limits" statements don't I in openerp-server.conf?

Just made a Database.  Is faster with 4 Gig I can see that already. 
Killed for a bit my "go to virtual workstation to get some ram"

**Comment by DocCyblade** [comment]
Yes in the conf file just systemctl restart openerp-server when done

**Comment by l-arnold** [comment]
I am going to work in Reverse.  I have 4 Gig Build and I will run with it so #55 first.

**Comment by l-arnold** [comment]
Do both work?

systemctl restart openerp-server
systemctl restart openerp-server.service

**Comment by l-arnold** [comment]
Set Soft to 256 mb  268435456
Set Hard to 3 GB  3221225472
On limits with converter:  http://www.whatsabyte.com/P1/byteconverter.htm

Handy Dandy, thanks

**Comment by l-arnold** [comment]
I realize cheating a bit starting installing all with 4gb rather than 1 gb.

Will do a full test later with 1 GB as well and not just swap it over (may also swap it over to see if the Big 4G buid dogs down)

**Comment by DocCyblade** [comment]
Remember that during the install the virtual memory or swap is set

**Comment by l-arnold** [comment]
In TKL or inbthe VM?

**Comment by l-arnold** [comment]
Note that these are "App" Level Modules.  Good Core to look at.   There are more Modules available if the "Apps" button is clicked off in "Local Modules".

 Also Note that If I take my database in (which I can do) I will trip up when I start working with Addons that are not in My directory structure and will fail if I go certain directions.  Need to fix that.

**Comment by l-arnold** [comment]
You are right about Swap file.  Need to dial it down.  Using 4 gb though ram now is only 2 gb  https://github.com/DocCyblade/tkl-odoo/issues/55

Wonder if I can reset that somehow in TKL setup?

**Comment by l-arnold** [comment]
Posted to wrong Issue set:  -> to https://github.com/DocCyblade/tkl-odoo/issues/55#issuecomment-148841003  for 4gb setup/ dropping to 2 gb.

**Comment by l-arnold** [comment]
Keep list of things tested here only. Add comments if any issues only.

Test List:
- [x] ISO Live Preview (Basic new database and module) **Fails** with 512MB RAM would need 1GB
- [x] ISO Install Guided Setup all
- [x] ISO Install Guided Setup LVM (Defaults)
- [x] First Boot: Signup for email alerts
- [x] First Boot: Updates
- [x] Create new database
- [x] Update Company Info
- [x] Add two users
- [x] Delete user
- [x] Install and configure all local modules
- [ ] Test Modules (Basic function of each)
- [ ] CRM
- [ ] Social Network
- [ ] Online Billing
- [ ] Point of Sale
- [ ] Project Management
- [ ] Notes
- [ ] Issue Tracking
- [ ] Accounting and Finance
- [ ] Survey
- [ ] Sales Management
- [ ] Warehouse Management
- [ ] Instant Messaging
- [ ] MRP
- [ ] Purchase Management
- [ ] Employee Directory
- [ ] Timesheets
- [ ] Recruitment Process
- [ ] Leave Management
- [ ] Expense Tracker
- [ ] Employee Appraisals
- [ ] Calendar
- [ ] Address Book
- [ ] Gamification
- [ ] Live Chat
- [ ] Odoo Live Support
- [ ] Lunch Orders
- [ ] Website Builder
- [ ] Blogs
- [ ] Online Events
- [ ] Forum
- [ ] eCommerce
- [ ] Fleet Management

**Comment by l-arnold** [comment]
HTOP does not install to Live CD/  500mb HD in place. (virtual memory I assume)  
Never did a LiveCD test before.

CRM Installs
Sales Management Installs

Quotation Renders for Print and EMAIL OK.

**Comment by l-arnold** [comment]
Will Do Guided Install now.

**Comment by l-arnold** [comment]
HTOP Installed.  1 GB Ram, 1 Processor
With 1 Database and Sales Management only installed, 61 % of Ram Being used.
HTOP  says

500 mb out of 1000mb being used
2 out of 1019 Swap being used.

**Comment by DocCyblade** [comment]
@l-arnold - When you are done testing, post your final thoughts in #50 and close this

**Comment by l-arnold** [comment]
650 mb out of 1000 MB being used.

Not Much Installed.  Sales Managment whcih brings some others.

Now CRM 661 mb.

Several more now at: 753 mb.

Note that "Survey" loads Website with it.

**Comment by l-arnold** [comment]
Switch to List view in Local Modules.
Select "not installed"
Select "all"
Choose "Module Immediate Install"

Seems to be doing a whole Batch now.
Yes!

---

nope, don't do that

---

Traceback (most recent call last):
  File "/opt/openerp/odoo/openerp/http.py", line 537, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/opt/openerp/odoo/openerp/http.py", line 574, in dispatch
    result = self._call_function(*_self.params)
  File "/opt/openerp/odoo/openerp/http.py", line 310, in _call_function
    return checked_call(self.db, *args, *_kwargs)
  File "/opt/openerp/odoo/openerp/service/model.py", line 118, in wrapper
    return f(dbname, _args, *_kwargs)
  File "/opt/openerp/odoo/openerp/http.py", line 307, in checked_call
    return self.endpoint(_a, *_kw)
  File "/opt/openerp/odoo/openerp/http.py", line 803, in __call__
    return self.method(_args, *_kw)
  File "/opt/openerp/odoo/openerp/http.py", line 403, in response_wrap
    response = f(_args, *_kw)
  File "/opt/openerp/odoo/addons/web/controllers/main.py", line 1255, in run
    [action_id], request.context)
  File "/opt/openerp/odoo/openerp/http.py", line 908, in proxy
    result = meth(cr, request.uid, _args, *_kw)
  File "/opt/openerp/odoo/openerp/api.py", line 250, in wrapper
    return old_api(self, _args, *_kwargs)
  File "/opt/openerp/odoo/openerp/addons/base/ir/ir_actions.py", line 1002, in run
    res = func(cr, uid, action, eval_context=eval_context, context=run_context)
  File "/opt/openerp/odoo/openerp/api.py", line 250, in wrapper
    return old_api(self, _args, *_kwargs)
  File "/opt/openerp/odoo/addons/website/models/ir_actions.py", line 62, in run_action_code_multi
    res = super(actions_server, self).run_action_code_multi(cr, uid, action, eval_context, context)
  File "/opt/openerp/odoo/openerp/api.py", line 250, in wrapper
    return old_api(self, _args, *_kwargs)
  File "/opt/openerp/odoo/openerp/addons/base/ir/ir_actions.py", line 836, in run_action_code_multi
    eval(action.code.strip(), eval_context, mode="exec", nocopy=True)  # nocopy allows to return 'action'
  File "/opt/openerp/odoo/openerp/tools/safe_eval.py", line 314, in safe_eval
    return eval(c, globals_dict, locals_dict)
  File "", line 1, in <module>
  File "/opt/openerp/odoo/openerp/api.py", line 250, in wrapper
    return old_api(self, _args, *_kwargs)
  File "/opt/openerp/odoo/openerp/addons/base/module/module.py", line 447, in button_immediate_install
    return self._button_immediate_function(cr, uid, ids, self.button_install, context=context)
  File "/opt/openerp/odoo/openerp/api.py", line 250, in wrapper
    return old_api(self, _args, *_kwargs)
  File "/opt/openerp/odoo/openerp/addons/base/module/module.py", line 495, in _button_immediate_function
    registry = openerp.modules.registry.RegistryManager.new(cr.dbname, update_module=True)
  File "/opt/openerp/odoo/openerp/modules/registry.py", line 370, in new
    openerp.modules.load_modules(registry._db, force_demo, status, update_module)
  File "/opt/openerp/odoo/openerp/modules/loading.py", line 355, in load_modules
    loaded_modules, update_module)
  File "/opt/openerp/odoo/openerp/modules/loading.py", line 255, in load_marked_modules
    loaded, processed = load_module_graph(cr, graph, progressdict, report=report, skip_modules=loaded_modules, perform_checks=perform_checks)
  File "/opt/openerp/odoo/openerp/modules/loading.py", line 179, in load_module_graph
    _load_data(cr, module_name, idref, mode, kind='demo')
  File "/opt/openerp/odoo/openerp/modules/loading.py", line 118, in _load_data
    tools.convert_file(cr, module_name, filename, idref, mode, noupdate, kind, report)
  File "/opt/openerp/odoo/openerp/tools/convert.py", line 901, in convert_file
    convert_xml_import(cr, module, fp, idref, mode, noupdate, report)
  File "/opt/openerp/odoo/openerp/tools/convert.py", line 987, in convert_xml_import
    obj.parse(doc.getroot(), mode=mode)
  File "/opt/openerp/odoo/openerp/tools/convert.py", line 853, in parse
    self._tags[rec.tag](self.cr, rec, n, mode=mode)
  File "/opt/openerp/odoo/openerp/tools/convert.py", line 763, in _tag_record
    id = self.pool['ir.model.data']._update(cr, self.uid, rec_model, self.module, res, rec_id or False, not self.isnoupdate(data_node), noupdate=self.isnoupdate(data_node), mode=self.mode, context=rec_context )
  File "/opt/openerp/odoo/openerp/api.py", line 250, in wrapper
    return old_api(self, _args, *_kwargs)
  File "/opt/openerp/odoo/openerp/addons/base/ir/ir_model.py", line 1052, in _update
    res_id = model_obj.create(cr, uid, values, context=context)
  File "/opt/openerp/odoo/openerp/api.py", line 250, in wrapper
    return old_api(self, _args, *_kwargs)
  File "/opt/openerp/odoo/addons/product/product.py", line 1185, in create
    return super(product_product, self).create(cr, uid, vals, context=ctx)
  File "/opt/openerp/odoo/openerp/api.py", line 250, in wrapper
    return old_api(self, _args, *_kwargs)
  File "/opt/openerp/odoo/addons/mail/mail_thread.py", line 381, in create
    thread_id = super(mail_thread, self).create(cr, uid, values, context=context)
  File "/opt/openerp/odoo/openerp/api.py", line 250, in wrapper
    return old_api(self, _args, *_kwargs)
  File "/opt/openerp/odoo/openerp/api.py", line 345, in old_api
    result = method(recs, _args, *_kwargs)
  File "/opt/openerp/odoo/openerp/models.py", line 4092, in create
    record = self.browse(self._create(old_vals))
  File "/opt/openerp/odoo/openerp/api.py", line 248, in wrapper
    return new_api(self, _args, *_kwargs)
  File "/opt/openerp/odoo/openerp/api.py", line 481, in new_api
    result = method(self._model, cr, uid, _args, *_kwargs)
  File "/opt/openerp/odoo/openerp/models.py", line 4148, in _create
    record_id = self.pool[table].create(cr, user, tocreate[table], context=context)
  File "/opt/openerp/odoo/openerp/api.py", line 250, in wrapper
    return old_api(self, _args, *_kwargs)
  File "/opt/openerp/odoo/addons/product/product.py", line 733, in create
    product_template_id = super(product_template, self).create(cr, uid, vals, context=context)
  File "/opt/openerp/odoo/openerp/api.py", line 250, in wrapper
    return old_api(self, _args, *_kwargs)
  File "/opt/openerp/odoo/addons/mail/mail_thread.py", line 381, in create
    thread_id = super(mail_thread, self).create(cr, uid, values, context=context)
  File "/opt/openerp/odoo/openerp/api.py", line 250, in wrapper
    return old_api(self, _args, *_kwargs)
  File "/opt/openerp/odoo/openerp/api.py", line 345, in old_api
    result = method(recs, _args, *_kwargs)
  File "/opt/openerp/odoo/openerp/models.py", line 4092, in create
    record = self.browse(self._create(old_vals))
  File "/opt/openerp/odoo/openerp/api.py", line 248, in wrapper
    return new_api(self, _args, *_kwargs)
  File "/opt/openerp/odoo/openerp/api.py", line 481, in new_api
    result = method(self._model, cr, uid, _args, *_kwargs)
  File "/opt/openerp/odoo/openerp/models.py", line 4277, in _create
    result += self._columns[field].set(cr, self, id_new, field, vals[field], user, rel_context) or []
  File "/opt/openerp/odoo/openerp/osv/fields.py", line 1477, in set
    self._fnct_inv(obj, cr, user, id, name, value, self._fnct_inv_arg, context)
  File "/opt/openerp/odoo/openerp/osv/fields.py", line 1713, in _property_write
    ir_property.set_multi(cr, uid, prop_name, obj._name, {id: value}, context=context)
  File "/opt/openerp/odoo/openerp/api.py", line 250, in wrapper
    return old_api(self, _args, *_kwargs)
  File "/opt/openerp/odoo/openerp/api.py", line 345, in old_api
    result = method(recs, _args, *_kwargs)
  File "/opt/openerp/odoo/openerp/addons/base/res/ir_property.py", line 224, in set_multi
    default_value = clean(self.get(name, model))
  File "/opt/openerp/odoo/openerp/api.py", line 248, in wrapper
    return new_api(self, _args, *_kwargs)
  File "/opt/openerp/odoo/openerp/api.py", line 481, in new_api
    result = method(self._model, cr, uid, _args, *_kwargs)
  File "/opt/openerp/odoo/openerp/addons/base/res/ir_property.py", line 150, in get
    domain = self._get_domain(cr, uid, name, model, context=context)
  File "/opt/openerp/odoo/openerp/api.py", line 250, in wrapper
    return old_api(self, _args, *_kwargs)
  File "/opt/openerp/odoo/openerp/addons/base/res/ir_property.py", line 170, in _get_domain
    cid = company._company_default_get(cr, uid, model, res[0], context=context)
  File "/opt/openerp/odoo/openerp/api.py", line 250, in wrapper
    return old_api(self, _args, *_kwargs)
  File "/opt/openerp/odoo/openerp/addons/base/res/res_company.py", line 235, in _company_default_get
    ('company_id', '=', self.pool['res.users']._get_company(cr, uid, context=context)),
  File "/opt/openerp/odoo/openerp/api.py", line 250, in wrapper
    return old_api(self, _args, *_kwargs)
  File "/opt/openerp/odoo/openerp/addons/base/res/res_users.py", line 245, in _get_company
    context=context, load='_classic_write')
  File "/opt/openerp/odoo/openerp/api.py", line 250, in wrapper
    return old_api(self, _args, *_kwargs)
  File "/opt/openerp/odoo/openerp/addons/base/res/res_users.py", line 897, in read
    res = super(users_view, self).read(cr, uid, ids, other_fields, context=context, load=load)
  File "/opt/openerp/odoo/openerp/api.py", line 250, in wrapper
    return old_api(self, _args, *_kwargs)
  File "/opt/openerp/odoo/openerp/addons/base/res/res_users.py", line 302, in read
    result = super(res_users, self).read(cr, uid, ids, fields=fields, context=context, load=load)
  File "/opt/openerp/odoo/openerp/api.py", line 250, in wrapper
    return old_api(self, _args, *_kwargs)
  File "/opt/openerp/odoo/openerp/models.py", line 3143, in read
    result = BaseModel.read(records, fields, load=load)
  File "/opt/openerp/odoo/openerp/api.py", line 248, in wrapper
    return new_api(self, _args, *_kwargs)
  File "/opt/openerp/odoo/openerp/models.py", line 3161, in read
    self.check_access_rights('read')
  File "/opt/openerp/odoo/openerp/api.py", line 248, in wrapper
    return new_api(self, _args, *_kwargs)
  File "/opt/openerp/odoo/openerp/api.py", line 460, in new_api
    result = method(self._model, cr, uid, _args, *_kwargs)
  File "/opt/openerp/odoo/openerp/models.py", line 3504, in check_access_rights
    return self.pool.get('ir.model.access').check(cr, uid, self._name, operation, raise_exception)
  File "/opt/openerp/odoo/openerp/api.py", line 250, in wrapper
    return old_api(self, _args, *_kwargs)
  File "/opt/openerp/odoo/openerp/service/server.py", line 723, in time_expired
    raise Exception('CPU time limit exceeded.')
ValueError: "" while evaluating
u"self.button_immediate_install(cr, uid, context.get('active_ids', []), context=context)"

**Comment by l-arnold** [comment]
(posted to wrong issue, seems like several things.)
Tried to do a bulk Install.  Don't do that.

Fleet Management ow it thinks they are all installed however.. it is not.
Choose "Upgrade" and it does come up as a Module however.

**Comment by l-arnold** [comment]
After the Upgrade it seems all the modules, including those I was "bulk installing" are there now.

Odoo things.

**Comment by l-arnold** [comment]
777 MB with seemingly all APPS installed.
out of 1000 mb

Swap is showing: 82 out of 1019

Seems you CAN run with 1 GB and 1 Processor.  I would say for a small installation, and small installations are budget minded.  

I think we are good.

Just loaded Google Calendar for Good Measure.

**Comment by l-arnold** [comment]
Just loaded Google Calendar for Good Measure.

PROBLEM.  I believe this is because of my "bulk install" however.

Odoo Server Error
Traceback (most recent call last):
  File "/opt/openerp/odoo/openerp/http.py", line 537, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/opt/openerp/odoo/openerp/http.py", line 574, in dispatch
    result = self._call_function(*_self.params)
  File "/opt/openerp/odoo/openerp/http.py", line 310, in _call_function
    return checked_call(self.db, *args, *_kwargs)
  File "/opt/openerp/odoo/openerp/service/model.py", line 118, in wrapper
    return f(dbname, _args, *_kwargs)
  File "/opt/openerp/odoo/openerp/http.py", line 307, in checked_call
    return self.endpoint(_a, *_kw)
  File "/opt/openerp/odoo/openerp/http.py", line 803, in __call__
    return self.method(_args, *_kw)
  File "/opt/openerp/odoo/openerp/http.py", line 403, in response_wrap
    response = f(_args, *_kw)
  File "/opt/openerp/odoo/addons/web/controllers/main.py", line 948, in call_button
    action = self._call_kw(model, method, args, {})
  File "/opt/openerp/odoo/addons/web/controllers/main.py", line 936, in _call_kw
    return getattr(request.registry.get(model), method)(request.cr, request.uid, _args, *_kwargs)
  File "/opt/openerp/odoo/openerp/api.py", line 250, in wrapper
    return old_api(self, _args, *_kwargs)
  File "/opt/openerp/odoo/openerp/addons/base/module/module.py", line 447, in button_immediate_install
    return self._button_immediate_function(cr, uid, ids, self.button_install, context=context)
  File "/opt/openerp/odoo/openerp/api.py", line 250, in wrapper
    return old_api(self, _args, *_kwargs)
  File "/opt/openerp/odoo/openerp/addons/base/module/module.py", line 495, in _button_immediate_function
    registry = openerp.modules.registry.RegistryManager.new(cr.dbname, update_module=True)
  File "/opt/openerp/odoo/openerp/modules/registry.py", line 370, in new
    openerp.modules.load_modules(registry._db, force_demo, status, update_module)
  File "/opt/openerp/odoo/openerp/modules/loading.py", line 355, in load_modules
    loaded_modules, update_module)
  File "/opt/openerp/odoo/openerp/modules/loading.py", line 255, in load_marked_modules
    loaded, processed = load_module_graph(cr, graph, progressdict, report=report, skip_modules=loaded_modules, perform_checks=perform_checks)
  File "/opt/openerp/odoo/openerp/modules/loading.py", line 176, in load_module_graph
    _load_data(cr, module_name, idref, mode, kind='data')
  File "/opt/openerp/odoo/openerp/modules/loading.py", line 118, in _load_data
    tools.convert_file(cr, module_name, filename, idref, mode, noupdate, kind, report)
  File "/opt/openerp/odoo/openerp/tools/convert.py", line 901, in convert_file
    convert_xml_import(cr, module, fp, idref, mode, noupdate, report)
  File "/opt/openerp/odoo/openerp/tools/convert.py", line 987, in convert_xml_import
    obj.parse(doc.getroot(), mode=mode)
  File "/opt/openerp/odoo/openerp/tools/convert.py", line 853, in parse
    self._tags[rec.tag](self.cr, rec, n, mode=mode)
  File "/opt/openerp/odoo/openerp/tools/convert.py", line 763, in _tag_record
    id = self.pool['ir.model.data']._update(cr, self.uid, rec_model, self.module, res, rec_id or False, not self.isnoupdate(data_node), noupdate=self.isnoupdate(data_node), mode=self.mode, context=rec_context )
  File "/opt/openerp/odoo/openerp/api.py", line 250, in wrapper
    return old_api(self, _args, *_kwargs)
  File "/opt/openerp/odoo/openerp/addons/base/ir/ir_model.py", line 1052, in _update
    res_id = model_obj.create(cr, uid, values, context=context)
  File "/opt/openerp/odoo/openerp/api.py", line 250, in wrapper
    return old_api(self, _args, *_kwargs)
  File "/opt/openerp/odoo/openerp/addons/base/ir/ir_ui_view.py", line 255, in create
    context=context)
  File "/opt/openerp/odoo/openerp/api.py", line 250, in wrapper
    return old_api(self, _args, *_kwargs)
  File "/opt/openerp/odoo/openerp/api.py", line 345, in old_api
    result = method(recs, _args, *_kwargs)
  File "/opt/openerp/odoo/openerp/models.py", line 4092, in create
    record = self.browse(self._create(old_vals))
  File "/opt/openerp/odoo/openerp/api.py", line 248, in wrapper
    return new_api(self, _args, *_kwargs)
  File "/opt/openerp/odoo/openerp/api.py", line 481, in new_api
    result = method(self._model, cr, uid, _args, *_kwargs)
  File "/opt/openerp/odoo/openerp/models.py", line 4283, in _create
    recs._validate_fields(vals)
  File "/opt/openerp/odoo/openerp/api.py", line 248, in wrapper
    return new_api(self, _args, *_kwargs)
  File "/opt/openerp/odoo/openerp/models.py", line 1272, in _validate_fields
    raise ValidationError('\n'.join(errors))
ParseError: "ValidateError
Field(s) `arch` failed against a constraint: Invalid view definition

Error details:
Field `in_group_22` does not exist

Error context:
View `res.users.form`
[view_id: 1528, xml_id: n/a, model: res.users, parent_id: 153]" while parsing /opt/openerp/odoo/addons/google_calendar/views/res_users.xml:4, near
<record id="view_users_form" model="ir.ui.view">
            <field name="name">res.users.form</field>
            <field name="model">res.users</field>
            <field name="inherit_id" ref="base.view_users_form"/>
            <field name="arch" type="xml">
                <notebook colspan="4" position="inside">
                    <page string="Calendar">
                        <group>
                            <field name="google_calendar_rtoken"/>
                            <field name="google_calendar_token"/>
                            <field name="google_calendar_token_validity"/>
                            <field name="google_calendar_last_sync_date"/>
                            <field name="google_calendar_cal_id"/>
                        </group>
                    </page>
                </notebook>
            </field>
        </record>

Add to this,
Google Calendar in Local Modules is
Visible
but no
Install, Upgrade, Uninstall buttons.

I broke it.

**Comment by l-arnold** [comment]
I don't know the cause.  But Google Calendar is not functioning properly.
Would need to bring all back to present, one at a time, to replicate properly.

I think this is good and an outside issue to our implementation.
Will do occassional tests.  

No experience with imlementing Google Services with Odoo.  Seems a bad idea somehow.
